---

- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for server folder to be generated
  wait_for:
    path: /var/lib/rancher/k3s/server
    state: present
    timeout: 360 

- name: Register file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Wait for node-token file to be generated
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    state: present
    timeout: 360

- name: Read Node Token from Master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store Master Token
  set_fact: 
   token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore file access 
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"

- name: Replace localhost in k3s.yaml with k3s master IP
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: '127.0.0.1'
    replace: '{{ master_ip }}'

- name: Retrieve kubectl config file from the master server.
  fetch: 
    src: /etc/rancher/k3s/k3s.yaml
    dest: files/k3s.yml
    flat: yes


#- debug: msg="Node TOKEN {{ token }}"
