apiVersion: v1
kind: Service
metadata:
  name: doge-wallet
  namespace: crypto
spec:
  ports:
  - name: doge-wallet
    port: 22556
    protocol: TCP
    targetPort: 22556
  selector:
    app: doge
    tier: wallet
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: doge-wallet-rpc
  namespace: crypto
spec:
  type: ClusterIP
  ports:
  - port: 22555
    name: doge-wallet-rpc
  selector:
    app: doge
    tier: wallet
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-wallet-doge
  namespace: crypto
  labels:
    name: mynfs-doge # name can be anything
spec:
  storageClassName: manual # same storage class as pvc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.27 # ip addres of nfs server
    path: "/media/nfs/" # path to directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-wallet-doge
  namespace: crypto
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany #  must be the same as PersistentVolume
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doge-wallet
  namespace: crypto
  labels:
    app: doge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doge
      tier: wallet
  template:
    metadata:
      labels:
        app: doge
        tier: wallet
    spec:
      containers:
      - image: boyroywax/doge-wallet:latest
        name: doge-wallet
        ports:
        - containerPort: 22556
          name: doge-wallet
          protocol: TCP
        - containerPort: 22555
          name: doge-wallet-rpc
          protocol: TCP
        volumeMounts:
        - mountPath: /root/.dogecoin
          name: dogecoin-vol1
          readOnly: false
          subPath: wallets/doge
      volumes:
      - name: dogecoin-vol1
        persistentVolumeClaim:
          claimName: nfs-pvc-wallet-doge
      restartPolicy: Always
status: {}
