FROM alpine:3.13.1
# Install CPUMiner-Multi
RUN set -x \
    # Runtime dependencies.
 && apk add --no-cache \
        libcurl \
        libgcc \
        libstdc++ \
        jansson-dev \
        gmp-dev \
        openssl \
        zlib-dev \
    # Build dependencies.
 && apk add --no-cache -t .build-deps \
        autoconf \
        automake \
        build-base \
        curl \
        curl-dev \
        git \
        openssl-dev \
    # Compile from source code.
 && git clone --recursive https://github.com/cpu-pool/cpuminer-opt-cpupower.git /tmp/cpuminer \
 && cd /tmp/cpuminer \
#  && chmod +x /tmp/cpuminer/build.sh \
#  && sh /tmp/cpuminer/build.sh \
#  && mv cpuminer /usr/local/bin/ 
 && chmod +x autogen.sh \
 && ./autogen.sh \
 && chmod +x configure \
#  && ./configure \
 && ./configure CFLAGS="-O3 -msse2 -march=native -Wall " --with-crypto --with-curl \
 && make \
 && mv cpuminer /usr/local/bin/

# Install Gosu
ENV GOSU_VERSION 1.12
RUN set -eux; \
    \
    apk add --no-cache --virtual .gosu-deps \
        ca-certificates \
        dpkg \
        gnupg \
    ; \
    \
    dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
    wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
    wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
    \
# verify the signature
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
    gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
    command -v gpgconf && gpgconf --kill all || :; \
    rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
    \
# clean up fetch dependencies
    apk del --no-network .gosu-deps; \
    \
    chmod +x /usr/local/bin/gosu; \
# verify that the binary works
    # gosu --version; \
    gosu nobody true

# Copy the entrypoint
WORKDIR /usr/local/bin
COPY ./entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

USER nobody
ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]
